[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
itertools = "0.10.5"
priority-queue = "1.3.1"
range_union_find = "0.4.4"
regex = "1.7.1"
