mod failing;
fn main() {
    // advent_of_code::q1();
    // advent_of_code::q2();
    // advent_of_code::q3a();
    // advent_of_code::q3b();
    // advent_of_code::q4a();
    // advent_of_code::q4b();
    // advent_of_code::q5a();
    // advent_of_code::q5b();
    // advent_of_code::q6a();
    // advent_of_code::q6b();
    // advent_of_code::q7();
    // advent_of_code::q8a();
    // advent_of_code::q8b();
    // advent_of_code::q9a();
    // advent_of_code::q9b();
    // advent_of_code::q10a();
    // advent_of_code::q10b();
    // advent_of_code::q11a();
    // advent_of_code::q11b();
    // advent_of_code::q12a();
    // advent_of_code::q12b();
    // advent_of_code::q13a();
    // advent_of_code::q13b();
    // advent_of_code::q13b_no_sort();
    // advent_of_code::q14a();
    // advent_of_code::q14b();
    // advent_of_code::q15a();
    // advent_of_code::q15b();
    // advent_of_code::q16a();
    // advent_of_code::q16b();
    // advent_of_code::q17a();
    // advent_of_code::q17b();
    // advent_of_code::q18a();
    // advent_of_code::q18b();
    // advent_of_code::q19();
    // advent_of_code::q20a();
    // advent_of_code::q20b();
    // advent_of_code::q21a();
    // advent_of_code::q21b();
    // advent_of_code::q22a();
    // TODO: aoc q22b
    advent_of_code::q23();
    advent_of_code::q24();
    advent_of_code::q25();
}
