fn main() {
    advent_of_code::q1();
    advent_of_code::q2();
    advent_of_code::q3a();
    advent_of_code::q3b();
    advent_of_code::q4a();
    advent_of_code::q4b();
    advent_of_code::q5a();
    advent_of_code::q5b();
    advent_of_code::q6a();
    advent_of_code::q6b();
    advent_of_code::q7();
    advent_of_code::q8a();
    advent_of_code::q8b();
    advent_of_code::q9a();
    advent_of_code::q9b();
    advent_of_code::q10a();
    advent_of_code::q10b();
    advent_of_code::q11a();
    advent_of_code::q11b();
    advent_of_code::q12a();
    advent_of_code::q12b();
}
